### ISSUE TITLE
deleted account!

### ISSUE THREAD

**Issue by aeims** [gheysar-official/tgwerewolf_game_helper#1]
I used your app to login telegram but after some minutes my account was deleted pls fix it or guide me to make it work properly by the way I have the required libraries installed, also I tried to log in manually but telegram said the number is banned.

**Comment by sajadGheysar** [comment]
its more about your account not the application. telegram is deleting new accounts after a client login into the account.
i suggest to create an account and use it for few weeks. after that login with app ( my app or others one ). it works well for me.
